* How to view changes made to files on a certain revision
#+BEGIN_SRC shell
svn diff -c <revision> path/to/repo
#+END_SRC

The =-c= indicates that you would like to look at a change set, but there
are many othter ways you can look at diffs and changesets.

For example, if you would like to know which files were changed (but not how),
you can issue

#+BEGIN_SRC shell
svn log -v -r <revision>
#+END_SRC

here =-r= is revision, =-v= is verbose, so that which file is changed 
can be seen, without =-v= only commit message can be seen.

Or, if you would like to show at the changes between two revisions (and not just for one commit)
#+BEGIN_SRC shell
svn diff -r <revA>:<revB> path/to/repo
#+END_SRC

-----

* External Items
Sometimes it is useful to construct a working copy that is made out
of a number of different checkouts. For example, you may want different files
or subdirectories to come from different locations in a repository, or
perhaps from a different repositories altogether. If you
want every user to have the same layout, you can define the =svn:externals=
properties to pull in the specified resource at the locations where they are
needed.

** for tortoise subversion
Let's say you check out a working copy of =/project1= to =D:\dev\project1=. 
Select the folder =D:\dev\project1=, right click and choose
=Windows Menu= -> =Properties= from the context menu. 
The Properties Dialog comes up. 
Then go to the Subversion tab. There, you can set properties. 
Click =Properties...=. In the properties dialog, 
either double click on the =svn:externals= if it already exists, 
or click on the =New...= button and select =externals= from the menu.
To add a new external, click the =New...= and then fill in the required 
information in the shown dialog.
* How do I revert an SVN commit
- undo a range
#+BEGIN_SRC shell
svn merge -r UPREV:LOWREV .
#+END_SRC

- undo single revision
#+BEGIN_SRC shell
svn merge -c -REV .
#+END_SRC


* svn log from a date to Head or from date to date
#+BEGIN_SRC shell
svn log -r {"2019-06-13 15:09"}:Head
#+END_SRC


#+BEGIN_SRC shell
svn log -r {2006-11-20}:{2006-11-29}
#+END_SRC


If you give a date without a timestamp, such as 2006-11-27, Subversion
assumes a time of 00:00:00, so looking for the most recent revision won't
return anything on the 27th.


If you want to include the 27th in your search, you can either specify the
27th with the time ({"2006-11-27 23:59"}), or just specify the next day
({2006-11-28}).

* update to a particular revision in svn
#+BEGIN_SRC shell
svn update -r <old revision number>
#+END_SRC
